[tool.poetry]
name = "statistics-101"
version = "0.1.0"
description = "Learning Statistics"
authors = ["stephan <sreindl@innitiative.at>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.1.3"
pandas = "^2.2.3"
polars = "^1.14.0"
matplotlib = "^3.9.2"
scipy = "^1.14.1"
icecream = "^2.1.3"
scikit-learn = "^1.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
